name: FMS Bug
description: Report a bug with the FMS or MCDU
title: "[BUG] - REPLACE ME"
labels: ["sys: fms", "type: verification required"]
assignees: []
body:
  - type: input
    attributes:
      label: Describe the bug
      description: Please describe the bug you have, with a clear and concise description
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      description: Please provide detailed steps to reproduce the issue you are having
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: Please describe the behaviour you are expecting, with reference if this is available to you
    validations:
      required: true
  - type: textarea
    attributes:
      label: Evidence
      description: |
        If you have any screenshots or videos that you can provide, please list them here.
        If you have any reference material which may help us, please list them here.
        
        Tip: You can drag and drop images into this box to upload them.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Simulator
      description: Which simulator are you using?
      options:
        - P3Dv4
        - P3Dv5
        - P3Dv6
        - Microsoft Flight Simulator 2020 (MSFS)
      multiple: true
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Crash
      description: Did this bug cause a crash?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Phase of flight
      description: What phase of flight were you in?
      options:
        - Pre-flight
        - Takeoff
        - Climb
        - Cruise
        - Descent
        - Approach
        - Landing
        - Post-flight
    validations:
      required: true
  - type: input
    attributes:
      label: Altitude
      description: What was your altitude?
    validations:
      required: false
  - type: markdown
    attributes:
      value: "### Itenerary"
  - type: input
    attributes:
      label: Departure
      description: What was your departure? Please provide this in ICAO format
      placeholder: KTPA
    validations:
      required: true
  - type: input
    attributes:
      label: Arrival
      description: What was your arrival? Please provide this in ICAO format
      placeholder: KTPA
    validations:
      required: true
  - type: input
    attributes:
      label: Cruise level
      description: What was your cruise level?
      placeholder: FL350
    validations:
      required: true
  - type: input
    attributes:
      label: ZFW
      description: What was your ZFW? Please provide your units
      placeholder: 61.2 LBS
    validations:
      required: true
  - type: input
    attributes:
      label: CG
      description: What was your CG?
      placeholder: 31%
    validations:
      required: true
  - type: input
    attributes:
      label: Fuel
      description: How much fuel was on-board? Please provide your units
      placeholder: 12.2 LBS
    validations:
      required: true
  - type: input
    attributes:
      label: Cost index
      description: What was your cost index set to?
      placeholder: "25"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Route
      description: Please provide your routing, including runway, SID, STAR and transitions used
    validations:
      required: true
  - type: textarea
    attributes:
      label: Location
      description: Please describe your location as best as you can. Ideally, this would be in reference to a waypoint
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Acknowledgement
        By submitting this issue, you understand that the TFDi Design team may need to contact you for more
        information regarding this bug. If we request information, and it is no response provided within 2 weeks
        your issue will be closed as "stale". You will be able to re-open the issue with a comment if this happens.
  - type: checkboxes
    attributes:
      label: Agreement
      description: By ticking this box, you understand and agree to the above statement
      options:
      - label: "Yes"
        required: true