name: Visual Bug
description: Report a bug with the model or textures
title: "[BUG] - REPLACE ME"
labels: ["sys: visual", "type: verification required"]
assignees: []
body:
  - type: input
    attributes:
      label: Describe the bug
      description: Please describe the bug you have, with a clear and concise description
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: Please describe the behaviour you are expecting, with reference if this is available to you.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Evidence
      description: |
        Reference material (such as photos or videos) are required, as well as screenshots or videos of the bug itself.
        
        Tip: You can drag and drop images into this box to upload them.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Simulator
      description: Which simulator are you using?
      options:
        - P3Dv4
        - P3Dv5
        - P3Dv6
        - Microsoft Flight Simulator 2020 (MSFS)
      multiple: true
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Acknowledgement
        By submitting this issue, you understand that the TFDi Design team may need to contact you for more
        information regarding this bug. If we request information, and it is no response provided within 2 weeks
        your issue will be closed as "stale". You will be able to re-open the issue with a comment if this happens.
  - type: checkboxes
    attributes:
      label: Agreement
      description: By ticking this box, you understand and agree to the above statement
      options:
      - label: "Yes"
        required: true